apply plugin: 'com.android.library'

dependencies {
    implementation fileTree(dir: 'bin', include: ['*.jar'])
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}

android {
    namespace "com.dwaallicht.permissions"
    compileSdk Integer.parseInt(project.findProperty('unity.compileSdkVersion') ?: '36')
    buildToolsVersion = project.findProperty('unity.buildToolsVersion') ?: '36.0.0'

    defaultConfig {
        minSdk Integer.parseInt(project.findProperty('unity.minSdkVersion') ?: '29')
        targetSdk Integer.parseInt(project.findProperty('unity.targetSdkVersion') ?: '36')
    }

    lint {
        abortOnError false
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            //java.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
        }
    }
}
